GraphApp/Models/Edge.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GraphApp.Models
{
    public class Edge
    {
        public int Id { get; set; }

        public int Source { get; set; }

        public int Target { get; set; }
    }
}

GraphApp/Models/Node.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GraphApp.Models
{
    public class Node
    {
        public int Id { get; set; }

        public string Label { get; set; }

        public IList<Edge> Edges { get; set; }

        public static IList<Node> CreateNodes(List<FrontEndService.NodeData> nodesService)
        {
            var nodes = new List<Node>();
            foreach (var nodeService in nodesService)
            {
                var edges = nodeService.Edges.Select(nr => new Edge { Id = nr.Id, Source = nr.Source, Target = nr.Target }).ToList();

                var node = new Node
                {
                    Id = nodeService.Id,
                    Label = nodeService.Label,
                    Edges = edges
                };

                nodes.Add(node);
            }

            return nodes;
        }
    }
}

GraphApp/ViewModels/MainViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using GraphApp.Models;

namespace GraphApp.ViewModels
{
    public class MainViewModel
    {
        public NodeJson[] nodes { get; set; }
        public EdgeJson[] edges { get; set; }
    }

    public class NodeJson
    {
        public NodeDataJson data { get; set; }
    }

    public class NodeDataJson
    {
        public int id { get; set; }
        public string Label { get; set; }
    }

    public class EdgeJson
    {
        public EdgeDataJson data { get; set; }
    }

    public class EdgeDataJson
    {
        public int id { get; set; }
        public int source { get; set; }
        public int target { get; set; }
    }
}

GraphApp/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GraphApp.Models;
using GraphApp.ViewModels;

namespace GraphApp.Controllers
{
    public class MainController : Controller
    {
        public ActionResult Index()
        {
            var service = new FrontEndService.FrontEndServiceClient();
            var nodes = Node.CreateNodes(service.GetNodes());

            var viewModel = new MainViewModel();
            viewModel.nodes = nodes.Select(n => new NodeJson { data = new NodeDataJson { id = n.Id, Label = n.Label } }).ToArray();
            viewModel.edges = nodes.SelectMany(n => n.Edges).Select(e => new EdgeJson { data = new EdgeDataJson { id = e.Id, source = e.Source, target = e.Target } }).ToArray();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult CalculateShortestPath(int rootEdge, int targetEdge)
        {
            var graphAppService = new GraphAppService.GraphAppClient();
            var shortestPath = graphAppService.CalculateShortestPath(rootEdge, targetEdge);
            return Json(shortestPath);
        }
    }
}

GraphApp/Views/Main/Index.cshtml
@model GraphApp.ViewModels.MainViewModel

@{
    ViewBag.Title = "Graph APP";
}

<div class="row">

    <div class="col-md-8">
        <div id="cy"></div>
        <div class="pull-right">
            <button id="btnCalculateShortestPath" type="button" class="btn btn-default">Calculate shortest path</button>
        </div>
    </div>

    <div class="col-md-3">
        <p>Please select the root node by left click.</p>

        <p>Please select the target node by right click.</p>
    </div>

</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            // constants
            const NODE_COLOR = '#666'
            const EDGE_COLOR = '#ccc'
            const NODE_START_COLOR = '#A8CD1B'
            const NODE_END_COLOR = '#990000'
            const EDGE_PATH_COLOR = '#CBE32D'

            // graph data
            var data = {
                nodes: @Html.Raw(Json.Encode(Model.nodes)),
                edges: @Html.Raw(Json.Encode(Model.edges)),
            };
            
            // cytoscape init
            var cy = cytoscape({

                container: $('#cy'),

                elements: data,

                style: [
                  {
                      selector: 'node',
                      style: {
                          'background-color': NODE_COLOR,
                          'label': 'data(Label)'
                      }
                  },

                  {
                      selector: 'edge',
                      style: {
                          'width': 3,
                          'line-color': EDGE_COLOR,
                          'target-arrow-color': EDGE_COLOR,
                          'target-arrow-shape': 'triangle',
                          'curve-style': 'bezier'
                      }
                  }
                ],

                layout: {
                    name: 'breadthfirst',
                    rows: 1
                },   
                zoomingEnabled: false

            });

            var rootEdge = null;
            var targetEdge = null;

            // node left click
            cy.on('tap', 'node', function (evt) {
                var node = evt.cyTarget;
                var id = node.id();

                if(targetEdge == id)
                    targetEdge = null;

                if(rootEdge != null)
                    cy.nodes('#'+rootEdge).style('background-color', NODE_COLOR)
                
                node.style('background-color', NODE_START_COLOR)
                rootEdge = id;

                cy.edges().style('line-color', EDGE_COLOR);

            });      
            
            // node right click
            cy.on('cxttap', 'node', function (evt) {
                var node = evt.cyTarget;
                var id = node.id();
                
                if(rootEdge == id)
                    rootEdge = null;

                if(targetEdge != null)
                    cy.nodes('#'+targetEdge).style('background-color', NODE_COLOR)

                node.style('background-color', NODE_END_COLOR)
                targetEdge = id;  

                cy.edges().style('line-color', EDGE_COLOR);
            });   

            // calculate click
            $('#btnCalculateShortestPath').on('click', function () {
                if(rootEdge != null && targetEdge != null){
                    $.ajax({
                        url: "@(Url.Action("CalculateShortestPath", "Main"))",
                        type: "POST",
                        data: { rootEdge: rootEdge, targetEdge: targetEdge},
                        cache: false,
                        async: true,
                        success: function (data) {
                            // change edges colors
                            cy.edges().style('line-color', EDGE_COLOR);
                            $.each(data, function( i, val ) {
                                cy.edges('#'+val).style('line-color', EDGE_PATH_COLOR);
                            });
                        }
                    });
                }else{
                    alert("Please select the root and the target node.")
                }

            });

            function setDefaultNodesColor(){
                cy.nodes.style('background-color', NODE_COLOR);
            }

        });
    </script>
}

@Scripts.Render("~/bundles/cytoscape")

GraphApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Graph APP</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>